spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3308/test?serverTimezone=UTC
    username: root
    hikari:
      # 用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1
      # 连接超时时间
      connection-timeout: 60000
      # 空闲连接超时时间
      idle-timeout: 500000
      # 连接最大存活时间
      max-lifetime: 540000
      # 最大连接数
      maximum-pool-size: 20
      # 最小空闲连接
      minimum-idle: 10
