server:
  port: 10388
  servlet:
    context-path: "/WRMSPharmAUX"

spring:
  profiles:
    active: test
  output:
    ansi:
      enabled: NEVER

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  flyway:
    cleanDisabled: true
    enabled: true
    baselineOnMigrate: false
    locations: classpath:database/migrations
      
mybatis:
  mapper-locations: classpath:com/lachesis/windranger/pharmaux/mapping/*.xml
  configuration:
      map-underscore-to-camel-case: true
  
logging:
  config: classpath:logs/logback-spring.xml
  root-level: info
  
flume:
 error:
  flumeAgents: 10.2.3.149:6666
 debug:
  flumeAgents: 10.2.3.149:6667
 info:
  flumeAgents: 10.2.3.149:6668

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  datasource:
    name: dev
		url: jdbc:mysql://1.1.1.1:3306/windranger_pharmaux?characterEncoding=utf8
    username: user
    password: Lachesis-mh_1024
    testConnectMaxWait: 3000

---

spring:
  profiles: test
  datasource:
    name: prod
		url: jdbc:mysql://1.1.1.1:3306/windranger_pharmaux?characterEncoding=utf8
    username: user
    password: 123456
    testConnectMaxWait: 3000
    
---

spring:
  profiles: prod
  datasource:
    name: prod
    url: jdbc:mysql://localhost:3306/windranger_pharmaux?characterEncoding=utf8
    username: user
    password: 123456
    testConnectMaxWait: 3000
  
    
